//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnnualPlan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnnualPlan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.AnnualPlan", typeof(AnnualPlan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norki amerykańskie.
        /// </summary>
        internal static string AmericanMinks {
            get {
                return ResourceManager.GetString("AmericanMinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to woliery.
        /// </summary>
        internal static string Aviaries {
            get {
                return ResourceManager.GetString("Aviaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borsuki.
        /// </summary>
        internal static string Badgers {
            get {
                return ResourceManager.GetString("Badgers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasy zaporowe.
        /// </summary>
        internal static string Barriers {
            get {
                return ResourceManager.GetString("Barriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planowana liczebność zwierzyny grubej przed okresem polowań.
        /// </summary>
        internal static string BigGamePlanBeforeHuntSeason {
            get {
                return ResourceManager.GetString("BigGamePlanBeforeHuntSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziki.
        /// </summary>
        internal static string Boars {
            get {
                return ResourceManager.GetString("Boars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przychody ze sprzedaży tusz zwierzyny płowej.
        /// </summary>
        internal static string CarcassesRevenues {
            get {
                return ResourceManager.GetString("CarcassesRevenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w tym : kwota wypłaconych odszkodowań łowieckich.
        /// </summary>
        internal static string Compensation {
            get {
                return ResourceManager.GetString("Compensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba osób zatrudnionych w oparciu o umowę o pracę w celu  wykonywania zadań z zakresu gospodarki łowieckiej.
        /// </summary>
        internal static string ContractEmployees {
            get {
                return ResourceManager.GetString("ContractEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łyski.
        /// </summary>
        internal static string Coots {
            get {
                return ResourceManager.GetString("Coots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszty poniesione na prowadzenie gospodarki łowieckiej.
        /// </summary>
        internal static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odstrzał szt..
        /// </summary>
        internal static string CullPieces {
            get {
                return ResourceManager.GetString("CullPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan planowany do osiągnięcia w bieżącym roku gospodarczym {0} / {1}.
        /// </summary>
        internal static string CurrentYearPlan {
            get {
                return ResourceManager.GetString("CurrentYearPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powierzchnia zredukowana upraw rolnych uszkodzonych przez zwierzęta łowne.
        /// </summary>
        internal static string DamagedArea {
            get {
                return ResourceManager.GetString("DamagedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byki razem.
        /// </summary>
        internal static string DeerBulls {
            get {
                return ResourceManager.GetString("DeerBulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cielęta.
        /// </summary>
        internal static string DeerCalves {
            get {
                return ResourceManager.GetString("DeerCalves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to łanie.
        /// </summary>
        internal static string DeerDoes {
            get {
                return ResourceManager.GetString("DeerDoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lizawki.
        /// </summary>
        internal static string DeerLickers {
            get {
                return ResourceManager.GetString("DeerLickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelenie Sika razem.
        /// </summary>
        internal static string DeersSikaTogether {
            get {
                return ResourceManager.GetString("DeersSikaTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelenie razem.
        /// </summary>
        internal static string DeersTogether {
            get {
                return ResourceManager.GetString("DeersTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane ogólne..
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gołębie grzywacze.
        /// </summary>
        internal static string Doves {
            get {
                return ResourceManager.GetString("Doves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objętościowa sucha.
        /// </summary>
        internal static string Dry {
            get {
                return ResourceManager.GetString("Dry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to czernice.
        /// </summary>
        internal static string DuckBlackberries {
            get {
                return ResourceManager.GetString("DuckBlackberries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to głowienki.
        /// </summary>
        internal static string DuckBrands {
            get {
                return ResourceManager.GetString("DuckBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to krzyżówki.
        /// </summary>
        internal static string DuckHybrid {
            get {
                return ResourceManager.GetString("DuckHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzikie kaczki razem.
        /// </summary>
        internal static string DucksTogether {
            get {
                return ResourceManager.GetString("DucksTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cyraneczki.
        /// </summary>
        internal static string DuckTeals {
            get {
                return ResourceManager.GetString("DuckTeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zagospodarowanie obwodu łowieckiego, szkody łowieckie..
        /// </summary>
        internal static string EconomyDetriment {
            get {
                return ResourceManager.GetString("EconomyDetriment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szacowana liczebność zwierząt na 10.03 {0}.
        /// </summary>
        internal static string EstimatedNumberGamesColonized10March {
            get {
                return ResourceManager.GetString("EstimatedNumberGamesColonized10March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daniele razem.
        /// </summary>
        internal static string FallowDeersTogether {
            get {
                return ResourceManager.GetString("FallowDeersTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zagrody.
        /// </summary>
        internal static string Farms {
            get {
                return ResourceManager.GetString("Farms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tchórze zwyczajne.
        /// </summary>
        internal static string Ferrets {
            get {
                return ResourceManager.GetString("Ferrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zagospodarowane przez dzierżawcę lub zarządcę łąki śródleśne i przyleśne.
        /// </summary>
        internal static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karma i sól.
        /// </summary>
        internal static string FoodAndSalt {
            get {
                return ResourceManager.GetString("FoodAndSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisy.
        /// </summary>
        internal static string Foxes {
            get {
                return ResourceManager.GetString("Foxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba zasiedlonych zwierząt do 10.03 poprzedniego roku gospodarczego.
        /// </summary>
        internal static string GamesColonized10March {
            get {
                return ResourceManager.GetString("GamesColonized10March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan zasiedleń w roku gospodarczym {0} / {1}.
        /// </summary>
        internal static string GamesColonizedPlan {
            get {
                return ResourceManager.GetString("GamesColonizedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optymalna liczba zwierząt zaplanowanych do pozyskania w {0} / {1} roku
        ///gospodarczym.
        /// </summary>
        internal static string GamesGainPlan {
            get {
                return ResourceManager.GetString("GamesGainPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatunki zwierząt łownych.
        /// </summary>
        internal static string GameTypes {
            get {
                return ResourceManager.GetString("GameTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to białoczelne.
        /// </summary>
        internal static string GooseAlbatrosses {
            get {
                return ResourceManager.GetString("GooseAlbatrosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zbożowe.
        /// </summary>
        internal static string GooseGrains {
            get {
                return ResourceManager.GetString("GooseGrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gęgawy.
        /// </summary>
        internal static string GooseGreylags {
            get {
                return ResourceManager.GetString("GooseGreylags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gęsi razem.
        /// </summary>
        internal static string GoosesTogether {
            get {
                return ResourceManager.GetString("GoosesTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zające szaraki.
        /// </summary>
        internal static string Hares {
            get {
                return ResourceManager.GetString("Hares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jarząbki.
        /// </summary>
        internal static string HazelGrouses {
            get {
                return ResourceManager.GetString("HazelGrouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roczny Plan Łowiecki na rok gospodarczy {0} / {1} oraz sprawozdanie z wykonania planu gospodarczego roku {2} / {1}.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urządzenia związane z prowadzeniem gospodarki łowieckiej.
        /// </summary>
        internal static string HuntingEquipment {
            get {
                return ResourceManager.GetString("HuntingEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objętościowa soczysta.
        /// </summary>
        internal static string Juicy {
            get {
                return ResourceManager.GetString("Juicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan na 10 marca roku, na który sporządza się plan {0} r..
        /// </summary>
        internal static string March10Condition {
            get {
                return ResourceManager.GetString("March10Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tumaki.
        /// </summary>
        internal static string Maren {
            get {
                return ResourceManager.GetString("Maren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kamionki.
        /// </summary>
        internal static string MarenKamionki {
            get {
                return ResourceManager.GetString("MarenKamionki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuny razem.
        /// </summary>
        internal static string MarensTogether {
            get {
                return ResourceManager.GetString("MarensTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna i maksymalna liczba zwierząt zaplanowana do pozyskania w roku gospodarczym {0} /{1}.
        /// </summary>
        internal static string MinMaxGameGainPlan {
            get {
                return ResourceManager.GetString("MinMaxGameGainPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byki.
        /// </summary>
        internal static string MooseBulls {
            get {
                return ResourceManager.GetString("MooseBulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to łoszaki.
        /// </summary>
        internal static string MooseCalves {
            get {
                return ResourceManager.GetString("MooseCalves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to klępy.
        /// </summary>
        internal static string MooseMares {
            get {
                return ResourceManager.GetString("MooseMares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łosie razem.
        /// </summary>
        internal static string MoosesTogether {
            get {
                return ResourceManager.GetString("MoosesTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jagnięta.
        /// </summary>
        internal static string MouflonLambs {
            get {
                return ResourceManager.GetString("MouflonLambs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tryki.
        /// </summary>
        internal static string MouflonRams {
            get {
                return ResourceManager.GetString("MouflonRams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muflony razem.
        /// </summary>
        internal static string Mouflons {
            get {
                return ResourceManager.GetString("Mouflons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owce.
        /// </summary>
        internal static string MouflonSheeps {
            get {
                return ResourceManager.GetString("MouflonSheeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piżmaki.
        /// </summary>
        internal static string Muskrats {
            get {
                return ResourceManager.GetString("Muskrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba osób zatrudnionych na innej podstawie niż umowa o pracę, lub powołanych, w celu wykonywania zadań z zakresu gospodarki łowieckiej.
        /// </summary>
        internal static string NonContractEmployees {
            get {
                return ResourceManager.GetString("NonContractEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obwód łowiecki nr 20, powierzchnia 4777 ha, w tym powierzchnia gruntów leśnych 4394 ha..
        /// </summary>
        internal static string Paragraph1st {
            get {
                return ResourceManager.GetString("Paragraph1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwo Wielkopolskie, Powiat Złotowski..
        /// </summary>
        internal static string Paragraph2nd {
            get {
                return ResourceManager.GetString("Paragraph2nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadleśnictwo Płytnica z siedzibą w Nowej Szwecji, Szwecja 6 78-600 Wałcz..
        /// </summary>
        internal static string Paragraph3rd {
            get {
                return ResourceManager.GetString("Paragraph3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regionalna Dyrekcja Lasów Państwowych Piła, 64-921 Piła - Kalina..
        /// </summary>
        internal static string Paragraph4th {
            get {
                return ResourceManager.GetString("Paragraph4th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarząd Okręgowy PZŁ, Piła, Al. Powstańców Wlkp. 190 64-920 Piła..
        /// </summary>
        internal static string Paragraph5th {
            get {
                return ResourceManager.GetString("Paragraph5th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzierżawca/lub zarządca, Koło Łowieckie nr 39 Literatów Polskich „Pióro” ul. Rostworowskego 6/2, 01-496 Warszawa..
        /// </summary>
        internal static string Paragraph6th {
            get {
                return ResourceManager.GetString("Paragraph6th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuropatwy.
        /// </summary>
        internal static string Partridges {
            get {
                return ResourceManager.GetString("Partridges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paśniki.
        /// </summary>
        internal static string Pastures {
            get {
                return ResourceManager.GetString("Pastures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bażanty.
        /// </summary>
        internal static string Pheasants {
            get {
                return ResourceManager.GetString("Pheasants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to treściwa.
        /// </summary>
        internal static string Pithy {
            get {
                return ResourceManager.GetString("Pithy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roczny Plan.
        /// </summary>
        internal static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan poprzedniego roku gospodarczego {0} / {1}.
        /// </summary>
        internal static string PreviousEconomyPlan {
            get {
                return ResourceManager.GetString("PreviousEconomyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonanie planu poprzedniego roku gospodarczego {0} / {1}.
        /// </summary>
        internal static string PreviousPlanExecution {
            get {
                return ResourceManager.GetString("PreviousPlanExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonanie planu pozyskania roku poprzed niego {0} / {1}.
        /// </summary>
        internal static string PreviousYearExecution {
            get {
                return ResourceManager.GetString("PreviousYearExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan pozyskania roku poprzedniego {0} / {1}.
        /// </summary>
        internal static string PreviousYearGainPlan {
            get {
                return ResourceManager.GetString("PreviousYearGainPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ambony.
        /// </summary>
        internal static string Pulpits {
            get {
                return ResourceManager.GetString("Pulpits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzikie króliki.
        /// </summary>
        internal static string Rabbits {
            get {
                return ResourceManager.GetString("Rabbits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenoty.
        /// </summary>
        internal static string RaccoonDogs {
            get {
                return ResourceManager.GetString("RaccoonDogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szopy pracze.
        /// </summary>
        internal static string Raccoons {
            get {
                return ResourceManager.GetString("Raccoons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kozy.
        /// </summary>
        internal static string RoeGoat {
            get {
                return ResourceManager.GetString("RoeGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to koźlęta.
        /// </summary>
        internal static string RoeGoatling {
            get {
                return ResourceManager.GetString("RoeGoatling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kozły razem.
        /// </summary>
        internal static string RoesRoebuckTogether {
            get {
                return ResourceManager.GetString("RoesRoebuckTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sarny razem.
        /// </summary>
        internal static string RoesTogether {
            get {
                return ResourceManager.GetString("RoesTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o przychodach ze sprzedaży tusz zwierzyny płowej i kosztach zagospodarowania obwodu..
        /// </summary>
        internal static string SalesRevenuesAndCosts {
            get {
                return ResourceManager.GetString("SalesRevenuesAndCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sól.
        /// </summary>
        internal static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zwierzyna drobna.
        /// </summary>
        internal static string SmallAnimals {
            get {
                return ResourceManager.GetString("SmallAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszczególnienie.
        /// </summary>
        internal static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poletka łowieckie(obszary obsiane lub obsadzone roślinami stanowiącymi żer dla zwierzyny na pniu).
        /// </summary>
        internal static string TrunkFood {
            get {
                return ResourceManager.GetString("TrunkFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka miary.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ogółem szt..
        /// </summary>
        internal static string UnitAltogetherPieces {
            get {
                return ResourceManager.GetString("UnitAltogetherPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odłów szt..
        /// </summary>
        internal static string UnitCatchAlivePieces {
            get {
                return ResourceManager.GetString("UnitCatchAlivePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ha.
        /// </summary>
        internal static string UnitHectare {
            get {
                return ResourceManager.GetString("UnitHectare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string UnitKilometers {
            get {
                return ResourceManager.GetString("UnitKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osoby.
        /// </summary>
        internal static string UnitPerson {
            get {
                return ResourceManager.GetString("UnitPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osoby / etaty.
        /// </summary>
        internal static string UnitPersonPartTime {
            get {
                return ResourceManager.GetString("UnitPersonPartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szt..
        /// </summary>
        internal static string UnitPiece {
            get {
                return ResourceManager.GetString("UnitPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tys. Zł.
        /// </summary>
        internal static string UnitThousandZlotych {
            get {
                return ResourceManager.GetString("UnitThousandZlotych", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tona.
        /// </summary>
        internal static string UnitTon {
            get {
                return ResourceManager.GetString("UnitTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ubytki szt..
        /// </summary>
        internal static string UnitWastagesPieces {
            get {
                return ResourceManager.GetString("UnitWastagesPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inne - wodopoje.
        /// </summary>
        internal static string WateringPlaces {
            get {
                return ResourceManager.GetString("WateringPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słonki.
        /// </summary>
        internal static string Woodcocks {
            get {
                return ResourceManager.GetString("Woodcocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
    }
}
